# Generated by Django 2.2.4 on 2019-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190820_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipes'),
        ),
    ]
